INSERT INTO categories (id, parent_id, name, created_at, updated_at) VALUES
(100, NULL, '教材・学業関連', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(200, NULL, 'ファッション・衣類', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(300, NULL, '一人暮らし応援・日用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(400, NULL, '趣味・エンタメ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(500, NULL, 'ハンドメイド・その他', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO categories (id, parent_id, name, created_at, updated_at) VALUES
(110, 100, '教科書', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120, 100, '参考書', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130, 100, '文房具', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140, 100, 'PC・タブレット・スマホ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(190, 100, 'その他', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(210, 200, '私服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(220, 200, '就活スーツ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(230, 200, 'バッグ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(240, 200, '衣装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(310, 300, '小型家電', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(320, 300, 'キッチン用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(330, 300, 'インテリア', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(340, 300, '消耗品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(410, 400, '本・マンガ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(420, 400, 'ゲーム・CD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(430, 400, 'サークル関連', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(510, 500, '手作り雑貨', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(520, 500, 'おまけ・試供品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
